#ifndef VIDEO_TIMING_H
#define	VIDEO_TIMING_H

#define _CYCLES_PER_US			16

#define _PAL_LINE_FULL_FRAME		625	// lines
#define _PAL_LINE_FRAME			312	// lines

#define _PAL_TIME_RENDERING_LINE	46	// µs
#define _PAL_LINE_DISPLAY		260	// lines
#define _PAL_LINE_MID			((_PAL_LINE_FRAME - _PAL_LINE_DISPLAY) / 2 + _PAL_LINE_DISPLAY / 2) // lines

#define _PAL_TIME_SCANLINE		64	// 64 µs
#define _PAL_TIME_HSYNC_PULSE		4.7	// 4.7 µs
#define _PAL_TIME_OUTPUT_START		12.5	// 12.05 + 0.45 µs

#define _PAL_CYCLES_SCANLINE		((_PAL_TIME_SCANLINE * _CYCLES_PER_US) - 1)
#define _PAL_CYCLES_HSYNC_PULSE		((_PAL_TIME_HSYNC_PULSE * _CYCLES_PER_US) - 1)
#define _PAL_CYCLES_OUTPUT_START	((_PAL_TIME_OUTPUT_START * _CYCLES_PER_US) - 1)

#define _PAL_TIME_VSYNC_SCANLINE		(_PAL_TIME_SCANLINE / 2)// µs
#define _PAL_TIME_VSYNC_PRE_EQUALIZING_PULSE	2.38	// 2.35 µs
#define _PAL_TIME_VSYNC_PULSE			27.32	// 27.3 µs

#define _PAL_CYCLES_VSYNC_SCANLINE		((_PAL_TIME_VSYNC_SCANLINE * _CYCLES_PER_US) - 1)
#define _PAL_CYCLES_VSYNC_EQUALIZING_PULSE	((_PAL_TIME_VSYNC_PRE_EQUALIZING_PULSE * _CYCLES_PER_US) - 1)
#define _PAL_CYCLES_VSYNC_PULSE			((_PAL_TIME_VSYNC_PULSE * _CYCLES_PER_US) - 1)

#define _PAL_LINE_FIRSTFRAME_END		311	// line# 310
#define _PAL_LINE_SECONDFRAME_START		318	// line# 317

#define _PAL_LINE_SECONDFRAME_END		624	// line# 622
#define _PAL_LINE_FIRSTFRAME_START		6	// line# 5

#endif
